server:
  port: 8080

#ZooKeeper
dubbo:
  registry:
    address: 47.105.131.58:2181
 
#Logger
logging:
  level:
    root: INFO

hwy: 
  callback: https://pushapi.bzlyplay.com/smsStatusReport/hwyReport